name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to Railway
      uses: railway-app/railway@v1
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: bpmn2dcr
      env:
        PORT: 80